SELECT ED3.CHILD_ID AS ID
FROM ECOLI_DATA ED
INNER JOIN
(
    SELECT CHILD.ID AS CHILD_ID, PARENT.PARENT_ID AS GRAND_PARENT_ID
    FROM ECOLI_DATA PARENT
    INNER JOIN ECOLI_DATA CHILD
    ON PARENT.ID = CHILD.PARENT_ID
) AS ED3
ON ED.ID = ED3.GRAND_PARENT_ID
WHERE 1 = 1
AND ED.PARENT_ID IS NULL
ORDER BY ED3.CHILD_ID
