WITH WIT_ECOLI_DATA AS (
    SELECT ED.PARENT_ID, COUNT(PARENT_ID) AS CHILD_COUNT
    FROM ECOLI_DATA ED
    GROUP BY ED.PARENT_ID
)
SELECT ED.ID, IFNULL(WED.CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA ED
LEFT JOIN WIT_ECOLI_DATA WED
ON ED.ID = WED.PARENT_ID
ORDER BY ED.ID
