-- 2021년에 가입한 전체 회원들 중 상품을 구매한 회원수와 상품을 구매한 회원의 비율
SELECT A.*, 
    ROUND(A.PURCHASED_USERS / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021) , 1) AS PUCHASED_RATIO
FROM (
    SELECT YEAR(SALES_DATE) AS YEAR, 
            MONTH(SALES_DATE) AS MONTH, 
            COUNT(DISTINCT OS.USER_ID) AS PURCHASED_USERS
    FROM USER_INFO UI
    INNER JOIN ONLINE_SALE OS
    ON UI.USER_ID = OS.USER_ID
    WHERE 1 = 1 
    AND YEAR(JOINED) = 2021
    GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
) A
ORDER BY A.YEAR, A.MONTH