WITH RECURSIVE GENERATION AS (
    SELECT CHILD.ID AS CHILD_ID, 1 AS GEN
    FROM ECOLI_DATA AS PARENT
    LEFT JOIN ECOLI_DATA AS CHILD
    ON PARENT.ID = CHILD.PARENT_ID
    WHERE PARENT.PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT CHILD.ID AS CHILD_ID, G.GEN + 1 AS GEN
    FROM ECOLI_DATA PARENT
    LEFT JOIN GENERATION G
    ON PARENT.ID = G.CHILD_ID
    LEFT JOIN ECOLI_DATA CHILD
    ON PARENT.ID = CHILD.PARENT_ID
    WHERE 1 = 1
    AND G.CHILD_ID IS NOT NULL
)
SELECT COUNT(*) AS COUNT, G.GEN AS GENERATION
FROM GENERATION G
WHERE G.CHILD_ID IS NULL
GROUP BY G.GEN
ORDER BY G.GEN