WITH A AS (
    SELECT ITEM_ID
    FROM ITEM_INFO
    WHERE RARITY = 'RARE'
)
SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM ITEM_INFO II
INNER JOIN ITEM_TREE IT
ON II.ITEM_ID = IT.ITEM_ID
INNER JOIN
(
    SELECT ITEM_ID
    FROM ITEM_INFO
    WHERE RARITY = 'RARE'
) A
ON IT.PARENT_ITEM_ID = A.ITEM_ID
WHERE 1 = 1
AND IT.PARENT_ITEM_ID IS NOT NULL
ORDER BY ITEM_ID DESC
