SELECT SED.ID, SED.GENOTYPE, ED.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA ED
LEFT JOIN ECOLI_DATA SED
ON ED.ID = SED.PARENT_ID
WHERE 1 = 1
AND SED.GENOTYPE &(ED.GENOTYPE) = ED.GENOTYPE
ORDER BY SED.ID