SELECT DI.ID, DI.EMAIL, DI.FIRST_NAME, DI.LAST_NAME
FROM DEVELOPERS DI
WHERE 1 = 1
AND SKILL_CODE &(SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') 
OR SKILL_CODE &(SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') 
ORDER BY DI.ID