-- 코드를 작성해주세요
SELECT A.YEAR, (A.MAX_SIZE - ED.SIZE_OF_COLONY) AS YEAR_DEV, ED.ID
FROM
(
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) A
INNER JOIN ECOLI_DATA ED
ON A.YEAR = YEAR(DIFFERENTIATION_DATE)
ORDER BY A.YEAR, YEAR_DEV