-- 코드를 작성해주세요
SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH
FROM 
(
    SELECT FI.FISH_TYPE, MAX(FI.LENGTH) AS MAX_LENGTH
    FROM FISH_INFO FI
    WHERE 1 = 1
    GROUP BY FISH_TYPE
) A
LEFT JOIN FISH_INFO FI
ON A.FISH_TYPE = FI.FISH_TYPE AND A.MAX_LENGTH = FI.LENGTH
INNER JOIN FISH_NAME_INFO FNI
ON A.FISH_TYPE = FNI.FISH_TYPE
WHERE 1 = 1
AND FI.ID IS NOT NULL
ORDER BY FI.ID