SELECT HG.SCORE, HG.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
FROM HR_DEPARTMENT HD
INNER JOIN HR_EMPLOYEES HE
ON HD.DEPT_ID = HE.DEPT_ID
INNER JOIN (
    SELECT EMP_NO, YEAR, SUM(SCORE) AS SCORE
    FROM HR_GRADE HG
    GROUP BY EMP_NO, YEAR
) AS HG
ON HE.EMP_NO = HG.EMP_NO
ORDER BY SCORE DESC
LIMIT 1
